# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0004_join_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='ip_address',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='none', max_length=120),
        ),
    ]
