# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0006_auto_20160922_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='none', max_length=120, unique=True),
        ),
    ]
