# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0008_auto_20160922_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='refered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer', to='joins.Join'),
        ),
    ]
